import React from 'react';
import "./Projects.css";
import starbucks from "../ProjectImages/starbucks.png";
import FR from "../ProjectImages/FR.png";
import Data from '../ProjectImages/DataScience.png';
import Robo from "../ProjectImages/robofriends.png";
const ProjectList = () => {
  return (
    <div>
      <div className="Projects">
        <div className="a-left">
          <div className="a-card bg"></div>
          <div className="a-card">
            <a href='https://sony9905.github.io/RoboFriends/' target="blank_">
              <img
                src={Robo}
                alt=""
                className="a-img"
              />
            </a>
          </div>
        </div>
        <div className="a-right">
          <h1 className="title">RoboFriends</h1>
          <p className="a-sub">
            Fun creative project using class based React and a free Robots API.
          </p>
          <p className="a-desc">
            Using the RoboHash api, https://robohash.org/, I created a responsive website that allows you to search through robot cards generated by mock data stored locally.
          </p>
          <a href='#Project2'>
            <button className='draw'>Next Project:</button>
          </a>
        </div>
      </div>
      <div className="Project2" id='Project2'>
        <div className="a-left">
          <div className="a-card bg"></div>
          <div className="a-card">
            <a href='https://stephanie-yung.github.io/capstone-frontend/#/' target="blank_">
            <img
              src={starbucks}
              alt=""
              className="a-img"
            />
            </a>
          </div>
        </div>
        <div className="a-right">
          <h1 className="title">Starbucks Clone</h1>
          <p className="a-sub">
            Working in an agile based environment, this Starbucks clone is created using functional React on the front-end and MondoDB/Flask for the back-end
          </p>
          <p className="a-desc">
            As part of a capstone project, Myself and 3 other invdivudals paired together and worked in an agile based work environment, working within 2 weeks sprints and collecting feedback from our Professor. In this Project we created a Starbucks clone that allows users to create custom Starbucks drinks that they normally would not be able to within the regular Starbucks app. The front-end is hosted by Github pages while the back-end is hosted by Heroku. 
          </p>
          <a href='#P3'>
            <button className='draw'>Next Project:</button>
          </a>
        </div>
      </div>
      <div className="Project3" id='P3'>
        <div className="a-left">
          <div className="a-card bg"></div>
          <div className="a-card">
            <a href='https://sony9905.github.io/DataScienceProject/#home' target="blank_">
            <img
              src={Data}
              alt=""
              className="a-img"
            />
            </a>
          </div>
        </div>
        <div className="a-right">
          <h1 className="title">Data-Science Study</h1>
          <p className="a-sub">
            A study showing a full analysis of NYC open data that demonstrates the utilization of python's libaries, such as pandas, seaborn and matplotlib. The website was created using vanilla Javascript, CSS and HTML5
          </p>
          <p className="a-desc">
          This website will display the full analysis of NYC open data and demonstrate the utilization of python's libaries, such as pandas, seaborn and matplotlib. The objective was to research the Demographic of nyc schools and discover if there is a correlation between race and poverty levels in schools. The goal was to determine whether there was a correlation between schools with a high number of POC students and poverty levels, and vice versa. Additonally, we attempted to determine the correlation between graduation rates and racial background.
          </p>
          <a href='#P4'>
            <button className='draw'>Next Project:</button>
          </a>
        </div>
      </div>
      <div className="Project4" id="P4">
        <div className="a-left">
          <div className="a-card bg"></div>
          <div className="a-card">
            <a href='https://sony9905.github.io/FR/' target="blank_">
            <img
              src={FR}
              alt=""
              className="a-img"
            />
            </a>
          </div>
        </div>
        <div className="a-right">
          <h1 className="title">Face Recognition App</h1>
          <p className="a-sub">
            Fun creative project using functional React to create a responsive front-end where users can upload images to detect Faces within the image. 
          </p>
          <p className="a-desc" style={{marginBottom: 35}} >
            In the course of learning the React Framework, I created a Facial Recognition App with a sign-in/Register page. Utilized node modeles such as TSparticles and the css framework: Tachyons. 
          </p>
          <a href='#Contact'>
            <button className='draw' onClick={()=> {
                        let pageHeight = window.innerHeight;
                        window.scrollBy(0, pageHeight);
                    }}>If you wish to contact me directly:</button>
          </a>
        </div>
      </div>
    </div>
  );
};

export default ProjectList;